# Configuration for CI build at https://travis-ci.org/spring-io/sagan

language: java

jdk:
  - oraclejdk8

node_js:
  - '0.10'

git:
  submodules: false

env:
  global:
    - GRADLE_OPTS="-Xmx1024m -Xms1024m"
    - TERM=dumb

script:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./gradlew deploy; else ./gradlew check; fi'

sudo: false

cache:
  directories:
  - $HOME/.gradle

notifications:
  hipchat:
    rooms:
      secure: RPubHrQ43LqAeS+OxGsYyCtFztn0XE3BHw5rcEdTs1ewqmC5XusNRuqfijeuHBNJNX1dM7RosdktnBV1C+Jc3auI+AJTt+lQ0PU4dBg3UbjOrdIB+pCaMrgpg+JvHqOrb6iw+D1naqnJyKTKsSEWe5/bUSWGA8nhD3iuKCWXOtg=
