---
applications:
- name: sagan-blue
  memory: 2G
  instances: 1
  domain: cfapps.io
  path: target/springframework-site-0.0.1.SNAPSHOT.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
- name: sagan-green
  memory: 2G
  instances: 1
  domain: cfapps.io
  path: target/springframework-site-0.0.1.SNAPSHOT.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
- name: sagan-indexer
  memory: 2G
  instances: 1
  host: sagan-indexer
  domain: cfapps.io
  path: target/springframework-site-0.0.1.SNAPSHOT.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
