project:
  artifactId: springframework-site
  name: Sagan
  version: X.X.X.X
  description: Sagan website

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}
  spring:
    profiles: ${spring.profiles.active:default} 

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jpa:
    hibernate:
      namingstrategy: org.hibernate.cfg.EJB3NamingStrategy

security:
  basic:
    path: ""
  user:
    password: ${ADMIN_PASSWORD:}

github:
  client:
    id: fb06c006c2ed62fe9e8b
    secret: 164264e3f6d70c7c21713b7fa64225cb8d6107b2

elasticsearch:   
  client:     
    endpoint: https://qlmsjwfa.api.qbox.io

---

spring:
  profiles: default,site
  main:
    sources: org.springframework.site.web.configuration.ApplicationConfiguration
  search:
    indexer:
      delay: 0
      base_url: http://localhost:8080

---

spring:
  profiles: indexer
  main:
    sources: org.springframework.site.indexer.configuration.IndexerConfiguration
search:
  indexer:
    delay: 0
server:
  port: 9000

---

spring:
  profiles: development
search:
  indexer:
    base_url: https://sagan.cfapps.io
elasticsearch:
  client:
    # gonçalo's account at qbox
    endpoint: https://qlmsjwfa.api.qbox.io

---

spring:
  profiles: staging
search:
  indexer:
    base_url: https://sagan-staging.cfapps.io
elasticsearch:
  client:
    # gonçalo's account at qbox
    endpoint: https://qlmsjwfa.api.qbox.io

---

spring:
  profiles: production
search:
  indexer:
    base_url: https://sagan-production.cfapps.io
elasticsearch:
  client:
    # chris' account at qbox
    endpoint: https://jgzosqbq.api.qbox.io

---

spring:
  profiles: acceptance
  database:
    url: jdbc:hsqldb:mem:acceptancetestdb
