---
applications:
- name: sagan-blue
  memory: 2G
  instances: 2
  domain: cfapps.io
  path: ../target/spring-io-site.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
- name: sagan-green
  memory: 2G
  instances: 2
  domain: cfapps.io
  path: ../target/spring-io-site.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
- name: sagan-indexer
  memory: 2G
  instances: 1
  host: sagan-indexer
  domain: cfapps.io
  path: ../target/spring-io-site.jar
  buildpack: https://github.com/cloudfoundry/java-buildpack
